eKreativeBundle\Entity\Message:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        topic:
            type: string
            length: '255'
            notnull: true
        body:
            type: text
        sent:
            type: boolean
    lifecycleCallbacks: {  }
    manyToOne:
        userTo:
            targetEntity: eKreativeBundle\Entity\User
            inversedBy: MessageTo
            joinColumn:
                name: user_to
                referencedColumnName: id